/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sv.edu.ues.occ.ingenieria.prn335_2024.cine.cineclient.boundary;

/**
 *
 * @author alexander
 */
public class FrmEscenario extends javax.swing.JFrame {

    /**
     * Creates new form FrmEscenario
     */
    public FrmEscenario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEscenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEscenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEscenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEscenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                PnlTipoSala frmTipoSala = new PnlTipoSala();
                frmTipoSala.setVisible(true);

                PnlTipoReserva frmTipoReserva = new PnlTipoReserva();
                frmTipoReserva.setVisible(true);

                PnlTipoProducto frmTipoProducto = new PnlTipoProducto();
                frmTipoProducto.setVisible(true);

                PnlTipoAsiento frmTipoAsiento = new PnlTipoAsiento();
                frmTipoAsiento.setVisible(true);

                PnlTipoPago frmTipoPago = new PnlTipoPago();
                frmTipoPago.setVisible(true);

                PnlTipoPelicula frmTipoPelicula = new PnlTipoPelicula();
                frmTipoPelicula.setVisible(true);

                PnlSucursal frmSucursal = new PnlSucursal();//no tendriamos que hacer un menu para que se vea cual pagina quiere ver el cliente?
                frmSucursal.setVisible(true);
                
                PnlAsiento frmAsiento = new PnlAsiento();
                frmAsiento.setVisible(true);
                
                PnlAsientoCaracteristica frmAsientocaracteristica = new PnlAsientoCaracteristica();
                frmAsientocaracteristica.setVisible(true);
                
                PnlPelicula frmPelicula = new PnlPelicula();
                frmPelicula.setVisible(true);
                
                PnlPeliculaCaracteristica frmPeliculaCaracteristica = new PnlPeliculaCaracteristica();
                frmPeliculaCaracteristica.setVisible(true);
                
               PnlProgramacion frmProgramacion = new PnlProgramacion();
                frmProgramacion.setVisible(true);
                
                 PnlReserva frmReserva = new PnlReserva();
                frmReserva.setVisible(true);
                
                 PnlSala frmSala = new PnlSala();
                frmSala.setVisible(true);
                
                PnlSalaCaracteristica frmSalaCaracteristica = new PnlSalaCaracteristica();
                frmSalaCaracteristica.setVisible(true);
                
                FrmEscenario frmEscenario = new FrmEscenario();
                frmEscenario.setDefaultCloseOperation(EXIT_ON_CLOSE);

                frmEscenario.setContentPane(frmTipoSala);
                //frmEscenario.setContentPane(frmSucursal); //ya la probe, si sirve
                //frmEscenario.setContentPane(frmTipoReserva); //ya la probe, si sirve
                // frmEscenario.setContentPane(frmTipoAsiento);//ya la probe, si sirve
                //frmEscenario.setContentPane(frmTipoPago);//ya la probe, si sirve
               // frmEscenario.setContentPane(frmTipoProducto);//NO SE PORQUE NO MUESTRA NINGUN DATO, HAY QUE REVISARLO
                //frmEscenario.setContentPane(frmTipoPelicula);//ya la probe, si sirve
               // frmEscenario.setContentPane(frmAsiento);//ya la probe, si sirve
              //frmEscenario.setContentPane(frmAsientocaracteristica);//ya la probe, si sirve
               //frmEscenario.setContentPane(frmPelicula);//ya la probe, si sirve
                //frmEscenario.setContentPane(frmPeliculaCaracteristica);//ya la probe, si sirve
             // frmEscenario.setContentPane(frmProgramacion);//NO SE PORQUE NO MUESTRA NINGUN DATO, HAY QUE REVISARLO
                 //frmEscenario.setContentPane(frmReserva);//ya la probe, si sirve
            // frmEscenario.setContentPane(frmSala);//ya la probe, si sirve
             frmEscenario.setContentPane(frmSalaCaracteristica);//ya la probe, si sirve
                frmEscenario.setVisible(true);
                frmEscenario.pack();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
