/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sv.edu.ues.occ.ingenieria.prn335_2024.cine.cineclient.boundary;

/**
 *
 * @author alexander
 */
public class FrmEscenario extends javax.swing.JFrame {

    /**
     * Creates new form FrmEscenario
     */
    public FrmEscenario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEscenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEscenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEscenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEscenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                FrmTipoSala frmTipoSala = new FrmTipoSala();
                frmTipoSala.setVisible(true);

                FrmTipoReserva frmTipoReserva = new FrmTipoReserva();
                frmTipoReserva.setVisible(true);

                FrmTipoProducto frmTipoProducto = new FrmTipoProducto();
                frmTipoProducto.setVisible(true);

                FrmTipoAsiento frmTipoAsiento = new FrmTipoAsiento();
                frmTipoAsiento.setVisible(true);

                FrmTipoPago frmTipoPago = new FrmTipoPago();
                frmTipoPago.setVisible(true);

                FrmTipoPelicula frmTipoPelicula = new FrmTipoPelicula();
                frmTipoPelicula.setVisible(true);

                FrmSucursal frmSucursal = new FrmSucursal();//no tendriamos que hacer un menu para que se vea cual pagina quiere ver el cliente?
                frmSucursal.setVisible(true);

                FrmEscenario frmEscenario = new FrmEscenario();
                frmEscenario.setDefaultCloseOperation(EXIT_ON_CLOSE);

                // frmEscenario.setContentPane(frmTipoSala);
                //frmEscenario.setContentPane(frmSucursal); //ya la probe, si sirve
                //frmEscenario.setContentPane(frmTipoReserva); //ya la probe, si sirve
                // frmEscenario.setContentPane(frmTipoAsiento);//ya la probe, si sirve
                //frmEscenario.setContentPane(frmTipoPago);//ya la probe, si sirve
                //frmEscenario.setContentPane(frmTipoProducto);//NO SE PORQUE NO MUESTRA NINGUN DATO, HAY QUE REVISARLO
                //frmEscenario.setContentPane(frmTipoPelicula);//ya la probe, si sirve
                frmEscenario.setVisible(true);
                frmEscenario.pack();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
